package: com.subex.interconnect.sitespecific.idea.taskcontroller.tasks.bill
is-delta: true
query-processor-required: true
output-folder: D:\Projects\Internal-GDO
birt-parameters: ["account","bill Profile" ]
extra-key-components: [ "extrakey1","extrakey2" ]
extra-value-components: [ "extravalue1","extravalue2"]

